b2drop-fedora:
  # build: .
  image: b2drop-fedora:latest
  hostname: owncloud
  domainname: localdomain
  ports:
    - "22"
    - "80"
    - "443"
  volumes:
    - ./b2share-bridge:/var/lib/owncloud/apps/b2share-bridge
    - ./b2drop-core:/usr/share/owncloud/themes/eudat

b2drop-centos:
  # build: .
  image: b2drop-centos:latest
  hostname: owncloud
  domainname: localdomain
  ports:
    - "22"
    - "80"
    - "443"
  volumes:
    - ./b2share-bridge:/var/www/html/owncloud/apps/b2share-bridge
    - ./b2drop-core:/var/www/html/owncloud/themes/b2drop
