fedora:
  build: fedora
  # image: b2drop-fedora:latest
  hostname: owncloud
  domainname: localdomain
  ports:
    - "22"
    - "80"
    - "443"
  volumes:
    - "./b2share-bridge:/var/lib/owncloud/apps/b2share-bridge"
    - "./b2drop-core:/usr/share/owncloud/themes/eudat"
  links:
    - mariadb:db

centos:
  build: centos
  # image: b2drop-centos:latest
  hostname: owncloud
  domainname: localdomain
  ports:
    - "22"
    - "80"
    - "443"
  volumes:
    - "./b2share-bridge:/var/www/html/owncloud/apps/b2share-bridge"
    - "./b2drop-core:/var/www/html/owncloud/themes/b2drop"
    - "./certs:/srv/certs:ro"
    - "./saml/saml.crt:/etc/shibboleth/sp-cert.pem:ro"
    - "./saml/saml.pem:/etc/shibboleth/sp-key.pem:ro"
    - "./saml/idp.pem:/etc/shibboleth/idp.pem:ro"
    - "./saml/shibboleth2.xml:/etc/shibboleth/shibboleth2.xml:ro"
    - "./saml/attribute-map.xml:/etc/shibboleth/attribute-map.xml:ro"
    - "./user_shib:/var/www/html/owncloud/apps/user_shib"
  links:
    - mariadb:db
  stop_signal: SIGWINCH

mariadb:
  image: centos/mariadb:latest
  hostname: mariadb
  domainname: localdomain
  expose:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=TopSecretPassWord
    - MYSQL_DATABASE=owncloud
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=dbpass
